name: Verify base branch of PR

on:
  pull_request:
    branches:
      - master

jobs:
  verify-base-branch:
    name: Verify base branch is dev
    runs-on: ubuntu-18.04
    steps:
      - name: Check base branch
        if: github.head_ref != 'dev'
        run: exit 1
